#200 create tribe page
U-ways/choppa pull request #205
Opened 2021-02-16 16:55 UTC by adamJUK

2021-02-16 19:34 UTC, U-ways commented
🚀

2021-02-16 19:34 UTC, U-ways approved these changes

2021-02-16 22:58 UTC, brett-taylor requested changes

2021-02-16 22:58 UTC, brett-taylor commented on src/frontend/src/config/router.js
> +    path: "/mytribes",
Imo this looks nicer `choppa.app/my-tribes` than `choppa.app/mytribes`

2021-02-16 22:58 UTC, brett-taylor commented on src/frontend/src/pages/DashboardPage.vue
> +        }));
aboslute nit (sorry): line break after the newToast method

2021-02-16 22:58 UTC, brett-taylor commented on src/frontend/src/pages/members/EditMemberPage.vue
>        if (this.deleteConfirmation === true) {
Why does `EditMemberPage` have to keep track off `deleteConfirmation`? Surely it should just pass to the `DoubleConfirmationButton` a `firstMessage` and `secondMessage` and the `click` event will only be emitted by the `DoubleConfirmationButton` on the second press?

2021-02-16 22:58 UTC, brett-taylor commented on src/frontend/src/pages/tribes/EditTribePage.vue
> +        this.chaptersInUse = await getChaptersByQuery({ url: this.tribe.relations.chapters });
If this is a brand new tribe why do we attempt to grab chapters in used by the tribe, surely it will always be empty? Can't we just set it to an empty array `[]` and save a network request

2021-02-16 23:12 UTC, adamJUK commented on src/frontend/src/pages/tribes/EditTribePage.vue
> +        this.chaptersInUse = await getChaptersByQuery({ url: this.tribe.relations.chapters });
Implemented.

2021-02-16 23:12 UTC, adamJUK commented on src/frontend/src/pages/DashboardPage.vue
> +        }));
Done.

2021-02-16 23:13 UTC, adamJUK commented on src/frontend/src/config/router.js
> +    path: "/mytribes",
Agreed. Has been changed.

2021-02-16 23:13 UTC, adamJUK commented on src/frontend/src/pages/members/EditMemberPage.vue
>        if (this.deleteConfirmation === true) {
Would this not be true for all instances where deleteConfirmation is in use?

2021-02-17 00:39 UTC, adamJUK commented on src/frontend/src/pages/members/EditMemberPage.vue
>        if (this.deleteConfirmation === true) {
Completed.

2021-02-17 00:41 UTC, merged